name: test01
on:
  schedule:
    - cron: '0 * * * *'  # Запуск каждый час в начале часа
  workflow_dispatch:  
jobs:
  test01:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
     #Setup Python   
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install software
        run: sudo apt-get install -y chromium-browser
      - name: Install the necessary packages
        run: pip install -r requirements.txt
      - name: Run the PyTest script
        run: python app.py vintagefellow22@gmail.com @Qwertych1234 cookies_vintagefellow.json profiles_vintagefellow.txt
